name: "Snyk Gradle - all projects"

on:
  push:
    branches:
      - 'demo*'  # Include any branch starting with demo

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Config'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          sudo npm install -g snyk-delta
          snyk auth ${SNYK_TOKEN}

      # Run Snyk OS
      - name: Run Snyk OS
        run: |
          ./snyk_delta_all_projects.sh --org=5dea2dc9-93fa-4227-8fd4-698534042bb0 --severity=low --remote-repo-url=gradle-test-cli 
          snyk monitor --all-projects --org=5dea2dc9-93fa-4227-8fd4-698534042bb0 --remote-repo-url=gradle-test-cli
        continue-on-error: true
